// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetApiV1SitesUserByUserIdData, GetApiV1SitesUserByUserIdResponse, PostApiV1SitesData, PostApiV1SitesResponse, GetApiV1SitesDomainByDomainData, GetApiV1SitesDomainByDomainResponse, PutApiV1SitesDomainByDomainData, PutApiV1SitesDomainByDomainResponse, DeleteApiV1SitesDomainByDomainData, DeleteApiV1SitesDomainByDomainResponse, GetApiV1GoalsSiteDomainByDomainData, GetApiV1GoalsSiteDomainByDomainResponse, PostApiV1GoalsSiteDomainByDomainData, PostApiV1GoalsSiteDomainByDomainResponse, GetApiV1GoalsSiteDomainByDomainGoalByNameData, GetApiV1GoalsSiteDomainByDomainGoalByNameResponse, PutApiV1GoalsSiteDomainByDomainGoalByNameData, PutApiV1GoalsSiteDomainByDomainGoalByNameResponse, DeleteApiV1GoalsSiteDomainByDomainGoalByNameData, DeleteApiV1GoalsSiteDomainByDomainGoalByNameResponse, GetApiV1SegmentsData, GetApiV1SegmentsResponse, PostApiV1SegmentsData, PostApiV1SegmentsResponse, GetApiV1SegmentsByDomainByNameData, GetApiV1SegmentsByDomainByNameResponse, PutApiV1SegmentsByDomainByNameData, PutApiV1SegmentsByDomainByNameResponse, DeleteApiV1SegmentsByDomainByNameData, DeleteApiV1SegmentsByDomainByNameResponse, PostApiV1AnalyticsSiteDomainGoalsStatsData, PostApiV1AnalyticsSiteDomainGoalsStatsResponse, PostApiV1AnalyticsSiteDomainReferrerStatsData, PostApiV1AnalyticsSiteDomainReferrerStatsResponse, PostApiV1AnalyticsAnalyticsData, PostApiV1AnalyticsAnalyticsResponse } from './types.gen';

export class SitesService {
    /**
     * Read Sites By User
     * @param data The data for the request.
     * @param data.userId The user ID to filter sites by
     * @param data.skip Number of records to skip (for pagination)
     * @param data.limit Maximum number of records to return (for pagination)
     * @returns Site Successful Response
     * @throws ApiError
     */
    public static getApiV1SitesUserByUserId(data: GetApiV1SitesUserByUserIdData): CancelablePromise<GetApiV1SitesUserByUserIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sites/user/{user_id}',
            path: {
                user_id: data.userId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                400: 'Invalid argument provided',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Create Site
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Site Successful Response
     * @throws ApiError
     */
    public static postApiV1Sites(data: PostApiV1SitesData): CancelablePromise<PostApiV1SitesResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sites/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                409: 'Resource already exists',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Read Site By Domain
     * @param data The data for the request.
     * @param data.domain The domain of the site to retrieve
     * @returns Site Successful Response
     * @throws ApiError
     */
    public static getApiV1SitesDomainByDomain(data: GetApiV1SitesDomainByDomainData): CancelablePromise<GetApiV1SitesDomainByDomainResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sites/domain/{domain}',
            path: {
                domain: data.domain
            },
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Update Site By Domain
     * @param data The data for the request.
     * @param data.domain The domain of the site to update
     * @param data.requestBody
     * @returns Site Successful Response
     * @throws ApiError
     */
    public static putApiV1SitesDomainByDomain(data: PutApiV1SitesDomainByDomainData): CancelablePromise<PutApiV1SitesDomainByDomainResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/sites/domain/{domain}',
            path: {
                domain: data.domain
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                409: 'Resource already exists',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Delete Site By Domain
     * @param data The data for the request.
     * @param data.domain The domain of the site to delete
     * @returns Site Successful Response
     * @throws ApiError
     */
    public static deleteApiV1SitesDomainByDomain(data: DeleteApiV1SitesDomainByDomainData): CancelablePromise<DeleteApiV1SitesDomainByDomainResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/sites/domain/{domain}',
            path: {
                domain: data.domain
            },
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
}

export class GoalsService {
    /**
     * Read Goals By Domain
     * @param data The data for the request.
     * @param data.domain The domain of the site to get goals for
     * @param data.skip Number of records to skip (for pagination)
     * @param data.limit Maximum number of records to return (for pagination)
     * @param data.goalType Filter goals by type (e.g., 'pageview', 'event', 'revenue')
     * @returns Goal Successful Response
     * @throws ApiError
     */
    public static getApiV1GoalsSiteDomainByDomain(data: GetApiV1GoalsSiteDomainByDomainData): CancelablePromise<GetApiV1GoalsSiteDomainByDomainResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/goals/site/domain/{domain}',
            path: {
                domain: data.domain
            },
            query: {
                skip: data.skip,
                limit: data.limit,
                goal_type: data.goalType
            },
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Create Goal By Domain
     * @param data The data for the request.
     * @param data.domain The domain of the site to create a goal for
     * @param data.requestBody
     * @returns Goal Successful Response
     * @throws ApiError
     */
    public static postApiV1GoalsSiteDomainByDomain(data: PostApiV1GoalsSiteDomainByDomainData): CancelablePromise<PostApiV1GoalsSiteDomainByDomainResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/goals/site/domain/{domain}',
            path: {
                domain: data.domain
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Read Goal By Domain And Name
     * @param data The data for the request.
     * @param data.domain The domain of the site
     * @param data.name The name of the goal to retrieve
     * @returns Goal Successful Response
     * @throws ApiError
     */
    public static getApiV1GoalsSiteDomainByDomainGoalByName(data: GetApiV1GoalsSiteDomainByDomainGoalByNameData): CancelablePromise<GetApiV1GoalsSiteDomainByDomainGoalByNameResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/goals/site/domain/{domain}/goal/{name}',
            path: {
                domain: data.domain,
                name: data.name
            },
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Update Goal By Domain And Name
     * @param data The data for the request.
     * @param data.domain The domain of the site
     * @param data.name The name of the goal to update
     * @param data.requestBody
     * @returns Goal Successful Response
     * @throws ApiError
     */
    public static putApiV1GoalsSiteDomainByDomainGoalByName(data: PutApiV1GoalsSiteDomainByDomainGoalByNameData): CancelablePromise<PutApiV1GoalsSiteDomainByDomainGoalByNameResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/goals/site/domain/{domain}/goal/{name}',
            path: {
                domain: data.domain,
                name: data.name
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Delete Goal By Domain And Name
     * @param data The data for the request.
     * @param data.domain The domain of the site
     * @param data.name The name of the goal to delete
     * @returns Goal Successful Response
     * @throws ApiError
     */
    public static deleteApiV1GoalsSiteDomainByDomainGoalByName(data: DeleteApiV1GoalsSiteDomainByDomainGoalByNameData): CancelablePromise<DeleteApiV1GoalsSiteDomainByDomainGoalByNameResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/goals/site/domain/{domain}/goal/{name}',
            path: {
                domain: data.domain,
                name: data.name
            },
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
}

export class SegmentsService {
    /**
     * Read Segments
     * @param data The data for the request.
     * @param data.domain Domain to filter segments by
     * @param data.skip Number of records to skip (for pagination)
     * @param data.limit Maximum number of records to return (for pagination)
     * @param data.dataType Filter segments by data type (e.g., 'does', 'does_not', 'time')
     * @returns DomainSegments Successful Response
     * @throws ApiError
     */
    public static getApiV1Segments(data: GetApiV1SegmentsData): CancelablePromise<GetApiV1SegmentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/segments/',
            query: {
                domain: data.domain,
                skip: data.skip,
                limit: data.limit,
                data_type: data.dataType
            },
            errors: {
                400: 'Invalid argument provided',
                409: 'Resource already exists',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Create Segment
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Segment Successful Response
     * @throws ApiError
     */
    public static postApiV1Segments(data: PostApiV1SegmentsData): CancelablePromise<PostApiV1SegmentsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/segments/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                409: 'Resource already exists',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Read Segment
     * @param data The data for the request.
     * @param data.domain The domain of the segment to retrieve
     * @param data.name The name of the segment to retrieve
     * @returns Segment Successful Response
     * @throws ApiError
     */
    public static getApiV1SegmentsByDomainByName(data: GetApiV1SegmentsByDomainByNameData): CancelablePromise<GetApiV1SegmentsByDomainByNameResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/segments/{domain}/{name}',
            path: {
                domain: data.domain,
                name: data.name
            },
            errors: {
                400: 'Invalid argument provided',
                409: 'Resource already exists',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Update Segment
     * @param data The data for the request.
     * @param data.domain The domain of the segment to update
     * @param data.name The name of the segment to update
     * @param data.requestBody
     * @returns Segment Successful Response
     * @throws ApiError
     */
    public static putApiV1SegmentsByDomainByName(data: PutApiV1SegmentsByDomainByNameData): CancelablePromise<PutApiV1SegmentsByDomainByNameResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/segments/{domain}/{name}',
            path: {
                domain: data.domain,
                name: data.name
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                409: 'Resource already exists',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Delete Segment
     * @param data The data for the request.
     * @param data.domain The domain of the segment to delete
     * @param data.name The name of the segment to delete
     * @returns Segment Successful Response
     * @throws ApiError
     */
    public static deleteApiV1SegmentsByDomainByName(data: DeleteApiV1SegmentsByDomainByNameData): CancelablePromise<DeleteApiV1SegmentsByDomainByNameResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/segments/{domain}/{name}',
            path: {
                domain: data.domain,
                name: data.name
            },
            errors: {
                400: 'Invalid argument provided',
                409: 'Resource already exists',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
}

export class AnalyticsService {
    /**
     * Get Goal Statistics
     * @param data The data for the request.
     * @param data.requestBody
     * @returns GoalStatsResponse Successful Response
     * @throws ApiError
     */
    public static postApiV1AnalyticsSiteDomainGoalsStats(data: PostApiV1AnalyticsSiteDomainGoalsStatsData): CancelablePromise<PostApiV1AnalyticsSiteDomainGoalsStatsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/analytics/site/domain/goals/stats',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Get Referrer Statistics
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ReferrerStatsResponse Successful Response
     * @throws ApiError
     */
    public static postApiV1AnalyticsSiteDomainReferrerStats(data: PostApiV1AnalyticsSiteDomainReferrerStatsData): CancelablePromise<PostApiV1AnalyticsSiteDomainReferrerStatsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/analytics/site/domain/referrer/stats',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
    /**
     * Get Segment Analytics
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static postApiV1AnalyticsAnalytics(data: PostApiV1AnalyticsAnalyticsData): CancelablePromise<PostApiV1AnalyticsAnalyticsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/analytics/analytics',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                400: 'Invalid argument provided',
                404: 'Requested resource not found',
                422: 'Validation Error',
                500: 'An unknown error occurred',
                503: 'Service is currently unavailable'
            }
        });
    }
    
}