const PERMISSIONS = new Map([
  ['/', ['dashboard']],
  ['/user', ['user']],
  ['/analytics/event', ['event']],
  ['/analytics/funnel', ['funnel']],
  ['/analytics/cohort', ['cohort']],
  ['/analytics/uninstall', ['uninstall']],
  ['/segment/live', ['live']],
  ['/segment/static', ['static']],
  ['/dataPlatform/management', ['management']],
  ['/dataPlatform/uploadData', ['uploadData']],
  ['/dataPlatform/alert', ['alert']],
  ['/overview', ['overview']],
  ['/channels/push', ['push']],
  ['/channels/webPush', ['webPush']],
  ['/channels/sms', ['sms']],
  ['/channels/email', ['email']],
  ['/channels/custom', ['custom']],
  ['/channels/whatsapp', ['whatsapp']],
  ['/channels/telegram', ['telegram']],
  ['/journey', ['journey']],
  ['/relays', ['relays']],
  ['/settings/channel', ['channel']],
  ['/settings/sdk', ['sdk']],
  ['/settings/webhook', ['webhook']],
  ['/settings/auditLog', ['auditLog']],
  ['/settings/restApi', ['restApi']],
  ['/settings/team', ['team']],
  ['/backOffice/financial', ['financial']],
  ['/backOffice/role', ['role']],
  ['/backOffice/users', ['users']],
  ['/backOffice/manageProducts', ['manageProducts']],
  ['/backOffice/createProduct', ['createProduct']],
  ['/backOffice/fileStorage', ['fileStorage']],
  ['/backOffice/configuration', ['configuration']],
]);

export { PERMISSIONS };
