// This file is auto-generated by @hey-api/openapi-ts

export const $DomainSegments = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain'
        },
        segments: {
            items: {
                '$ref': '#/components/schemas/SegmentInList'
            },
            type: 'array',
            title: 'Segments'
        }
    },
    type: 'object',
    required: ['domain', 'segments'],
    title: 'DomainSegments'
} as const;

export const $Goal = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        count_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count Method'
        },
        settings: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Settings'
        },
        site_uuid: {
            type: 'string',
            format: 'uuid',
            title: 'Site Uuid'
        },
        goal_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal Type'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['site_uuid'],
    title: 'Goal'
} as const;

export const $GoalCreate = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        count_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count Method'
        },
        settings: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Settings'
        },
        site_uuid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Site Uuid'
        },
        page_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Url'
        },
        referrer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Referrer'
        },
        url_pattern: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url Pattern'
        }
    },
    type: 'object',
    required: ['name', 'type'],
    title: 'GoalCreate'
} as const;

export const $GoalStats = {
    properties: {
        id: {
            type: 'string',
            title: 'Id',
            description: 'The goal ID'
        },
        name: {
            type: 'string',
            title: 'Name',
            description: 'The goal name'
        },
        type: {
            type: 'string',
            title: 'Type',
            description: 'The goal type'
        },
        count: {
            type: 'integer',
            title: 'Count',
            description: 'Total number of events'
        },
        total_user: {
            type: 'integer',
            title: 'Total User',
            description: 'Number of unique users'
        },
        event_per_user: {
            type: 'number',
            title: 'Event Per User',
            description: 'Average events per user'
        },
        utm_sources: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/UtmSourceStats'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Utm Sources',
            description: 'Breakdown by UTM sources if requested'
        }
    },
    type: 'object',
    required: ['id', 'name', 'type', 'count', 'total_user', 'event_per_user'],
    title: 'GoalStats'
} as const;

export const $GoalStatsRequest = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain',
            description: 'The domain of the site'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date',
            description: 'Start date (YYYY-MM-DD)'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date',
            description: 'End date (YYYY-MM-DD)'
        },
        goal_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal Type',
            description: "Filter by goal type (e.g., 'pageview', 'event')"
        }
    },
    type: 'object',
    required: ['domain'],
    title: 'GoalStatsRequest'
} as const;

export const $GoalStatsResponse = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date'
        },
        goals: {
            additionalProperties: {
                '$ref': '#/components/schemas/GoalStats'
            },
            type: 'object',
            title: 'Goals'
        }
    },
    type: 'object',
    required: ['domain', 'goals'],
    title: 'GoalStatsResponse'
} as const;

export const $GoalUpdate = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        count_method: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Count Method'
        },
        settings: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Settings'
        },
        event_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Event Type'
        },
        page_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Page Url'
        },
        referrer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Referrer'
        },
        url_pattern: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url Pattern'
        },
        element_text: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Element Text'
        },
        css_selector: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Css Selector'
        },
        time_threshold: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Time Threshold'
        },
        js_code: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Js Code'
        },
        form_selector: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Form Selector'
        }
    },
    type: 'object',
    title: 'GoalUpdate'
} as const;

export const $ReferrerCategory = {
    properties: {
        category: {
            type: 'string',
            title: 'Category',
            description: 'The referrer category (direct, referal, organic, social)'
        },
        total_user: {
            type: 'integer',
            title: 'Total User',
            description: 'Total number of users for this category'
        },
        new_user: {
            type: 'integer',
            title: 'New User',
            description: 'Number of new users for this category'
        },
        sessions: {
            type: 'integer',
            title: 'Sessions',
            description: 'Number of sessions for this category'
        },
        avg_time: {
            type: 'number',
            title: 'Avg Time',
            description: 'Average time on page for this category'
        },
        sources: {
            items: {
                '$ref': '#/components/schemas/SourceStats'
            },
            type: 'array',
            title: 'Sources',
            description: 'Detailed source stats within this category'
        }
    },
    type: 'object',
    required: ['category', 'total_user', 'new_user', 'sessions', 'avg_time'],
    title: 'ReferrerCategory'
} as const;

export const $ReferrerStatsRequest = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain',
            description: 'The domain of the site'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date',
            description: 'Start date (YYYY-MM-DD)'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date',
            description: 'End date (YYYY-MM-DD)'
        }
    },
    type: 'object',
    required: ['domain'],
    title: 'ReferrerStatsRequest'
} as const;

export const $ReferrerStatsResponse = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain',
            description: 'The domain of the site'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date',
            description: 'Start date (YYYY-MM-DD)'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date',
            description: 'End date (YYYY-MM-DD)'
        },
        referrer_stats: {
            items: {
                '$ref': '#/components/schemas/ReferrerCategory'
            },
            type: 'array',
            title: 'Referrer Stats',
            description: 'Statistics by referrer category'
        }
    },
    type: 'object',
    required: ['domain', 'referrer_stats'],
    title: 'ReferrerStatsResponse'
} as const;

export const $Segment = {
    properties: {
        domain: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Domain'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        conditions: {
            items: {
                '$ref': '#/components/schemas/SegmentCondition'
            },
            type: 'array',
            title: 'Conditions'
        },
        segment_uuid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid8'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Segment Uuid'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'conditions', 'created_at'],
    title: 'Segment'
} as const;

export const $SegmentAnalyticsRequest = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain',
            description: 'The domain of the site'
        },
        start_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Start Date',
            description: 'Start date (YYYY-MM-DD)'
        },
        end_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'End Date',
            description: 'End date (YYYY-MM-DD)'
        }
    },
    type: 'object',
    required: ['domain'],
    title: 'SegmentAnalyticsRequest'
} as const;

export const $SegmentCondition = {
    properties: {
        data_type: {
            type: 'string',
            title: 'Data Type'
        },
        condition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Condition'
        }
    },
    type: 'object',
    required: ['data_type', 'condition'],
    title: 'SegmentCondition',
    description: 'Segment condition model with validation based on data_type'
} as const;

export const $SegmentCreate = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        conditions: {
            items: {
                '$ref': '#/components/schemas/SegmentCondition'
            },
            type: 'array',
            title: 'Conditions'
        },
        domain: {
            type: 'string',
            title: 'Domain'
        }
    },
    type: 'object',
    required: ['name', 'conditions', 'domain'],
    title: 'SegmentCreate'
} as const;

export const $SegmentInList = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        conditions: {
            items: {
                '$ref': '#/components/schemas/SegmentCondition'
            },
            type: 'array',
            title: 'Conditions'
        },
        segment_uuid: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid8'
                },
                {
                    type: 'integer'
                },
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Segment Uuid'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'conditions'],
    title: 'SegmentInList'
} as const;

export const $SegmentUpdate = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        conditions: {
            anyOf: [
                {
                    items: {
                        '$ref': '#/components/schemas/SegmentCondition'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Conditions'
        }
    },
    type: 'object',
    title: 'SegmentUpdate'
} as const;

export const $Site = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public',
            default: false
        },
        stats_start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stats Start Date'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['domain', 'created_at'],
    title: 'Site'
} as const;

export const $SiteCreate = {
    properties: {
        domain: {
            type: 'string',
            title: 'Domain'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone',
            default: 'UTC'
        },
        public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public',
            default: false
        }
    },
    type: 'object',
    required: ['domain'],
    title: 'SiteCreate'
} as const;

export const $SiteUpdate = {
    properties: {
        domain: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Domain'
        },
        timezone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timezone'
        },
        public: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        stats_start_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stats Start Date'
        }
    },
    type: 'object',
    title: 'SiteUpdate'
} as const;

export const $SourceStats = {
    properties: {
        source: {
            type: 'string',
            title: 'Source',
            description: 'The specific referrer source'
        },
        total_user: {
            type: 'integer',
            title: 'Total User',
            description: 'Total number of users'
        },
        new_user: {
            type: 'integer',
            title: 'New User',
            description: 'Number of new users'
        },
        sessions: {
            type: 'integer',
            title: 'Sessions',
            description: 'Number of sessions'
        },
        avg_time: {
            type: 'number',
            title: 'Avg Time',
            description: 'Average time on page'
        }
    },
    type: 'object',
    required: ['source', 'total_user', 'new_user', 'sessions', 'avg_time'],
    title: 'SourceStats'
} as const;

export const $UtmSourceStats = {
    properties: {
        utm_source: {
            type: 'string',
            title: 'Utm Source',
            description: 'The UTM source'
        },
        count: {
            type: 'integer',
            title: 'Count',
            description: 'Total number of events for this UTM source'
        },
        total_user: {
            type: 'integer',
            title: 'Total User',
            description: 'Number of unique users for this UTM source'
        },
        event_per_user: {
            type: 'number',
            title: 'Event Per User',
            description: 'Average events per user for this UTM source'
        }
    },
    type: 'object',
    required: ['utm_source', 'count', 'total_user', 'event_per_user'],
    title: 'UtmSourceStats'
} as const;